import { Page } from '@playwright/test';

const BASE = process.env.BASE_URL || 'http://localhost:3000';

/**
 * Make an authenticated API request using the browser's native fetch.
 * This is 100% reliable for sharing the session/cookies after login.
 */
export async function apiRequest(page: Page, method: string, path: string, data?: any) {
  return await page.evaluate(async ({ method, path, data }) => {
    const response = await fetch(path, {
      method,
      headers: {
        'Content-Type': 'application/json',
      },
      credentials: 'include',
      body: data ? JSON.stringify(data) : undefined,
    });

    const isJson = response.headers.get('content-type')?.includes('application/json');
    const body = isJson ? await response.json() : await response.text();

    if (!response.ok) {
      console.error('API EVAL ERROR:', JSON.stringify(body));
      throw new Error(`API Error ${method} ${path}: ${response.status} ${response.statusText} - ${JSON.stringify(body)}`);
    }

    return body;
  }, { method, path, data });
}

// ─── Lifecycle Helpers ────────────────────────────────────────────────────────

export async function adminApproveRequest(page: Page, requestId: string) {
  return await apiRequest(page, 'PUT', `/api/admin/requests/${requestId}/approve`);
}

export async function createRequest(page: Page, overrides: any = {}) {
  const payload = {
    title: 'E2E Automated Request',
    description: 'This is a test request generated by Playwright API.',
    categoryId: 'test-category', // Depending on seeding, might need a real ID, but Prisma often works if we mock or if not strictly checked in tests
    countryId: 'test-country',
    cityId: 'test-city',
    budgetMin: 100,
    budgetMax: 500,
    currency: 'SAR',
    urgency: 'MEDIUM',
    visibility: 'PUBLIC',
    ...overrides
  };
  return await apiRequest(page, 'POST', '/api/requests', payload);
}

export async function submitOffer(page: Page, requestId: string, overrides: any = {}) {
  const payload = {
    price: 300,
    currency: 'SAR',
    estimatedDays: 5,
    message: 'We can fix this for you quickly.',
    ...overrides
  };
  return await apiRequest(page, 'POST', `/api/requests/${requestId}/offers`, payload);
}

export async function acceptOffer(page: Page, offerId: string) {
  return await apiRequest(page, 'PUT', `/api/offers/${offerId}`, { status: 'ACCEPTED' });
}

export async function markComplete(page: Page, requestId: string) {
  return await apiRequest(page, 'PUT', `/api/requests/${requestId}/complete`, {});
}

export async function sendMessage(page: Page, recipientId: string, content = 'Hello from E2E API') {
  // Catch errors if we *expect* it to fail (403), so tests can assert on the throw
  try {
    const res = await apiRequest(page, 'POST', '/api/messages', {
      recipientId,
      content,
    });
    return { ok: true, data: res };
  } catch (error: any) {
    return { ok: false, error: error.message };
  }
}
